<script setup lang="ts">
/**
 * AppIcon
 * feather-iconsを使用したアイコンを表示するコンポーネントです。
 */
import feather from 'feather-icons'
import { computed } from 'vue'

const props = defineProps<{
  name: string
  size?: 'sm' | 'md' | 'lg' | 'xl'
}>()

const svgContent = computed(() => {
  if (feather.icons[props.name as keyof typeof feather.icons]) {
    // Return raw SVG string generated by feather-icons
    return feather.icons[props.name as keyof typeof feather.icons].toSvg()
  }

  return ''
})
</script>

<template>
  <!-- eslint-disable vue/no-v-html -->
  <i
    class="c-icon"
    :class="[size ? `c-icon--${size}` : '']"
    v-html="svgContent"
  />
</template>

<style scoped lang="scss">
.c-icon {
  @include inline-flex-center;

  :deep(svg) {
    width: 100%;
    height: 100%;
  }

  &--sm {
    width: 14px;
    height: 14px;
  }

  &--md {
    width: 18px;
    height: 18px;
  }

  &--lg {
    width: 24px;
    height: 24px;
  }

  &--xl {
    width: 32px;
    height: 32px;
  }
}
</style>
