<template>
  <i class="c-icon" :class="[size ? `c-icon--${size}` : '']" v-html="svgContent"></i>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import feather from 'feather-icons'

const props = defineProps<{
  name: string
  size?: 'sm' | 'md' | 'lg' | 'xl'
}>()

const svgContent = computed(() => {
  if (feather.icons[props.name]) {
    // Return raw SVG string generated by feather-icons
    return feather.icons[props.name].toSvg()
  }
  return ''
})
</script>

<style scoped lang="scss">
.c-icon {
  // SVG styling is handled by global .c-icon
  display: inline-flex;
  align-items: center;
  justify-content: center;
  
  :deep(svg) {
    width: 100%;
    height: 100%;
  }
}
</style>
