/**
 * @fileoverview Drum Data Master
 * ケーブル用巻取ドラム（木枠等）の寸法・重量などのマスターデータを格納します。
 */
export const drumData = [
    {
        id: 'L1-1',
        category: 'L1',
        flange_diameter: '340',
        barrel_diameter: '200',
        outer_width: '300',
        inner_width: '240',
        shaft_hole: '50',
        weight: '5',
        max_winding_weight: '500'
    },
    {
        id: 'L1-2',
        category: 'L1',
        flange_diameter: '370',
        barrel_diameter: '200',
        outer_width: '300',
        inner_width: '240',
        shaft_hole: '50',
        weight: '5',
        max_winding_weight: '500'
    },
    {
        id: 'L1-3',
        category: 'L1',
        flange_diameter: '400',
        barrel_diameter: '200',
        outer_width: '300',
        inner_width: '240',
        shaft_hole: '50',
        weight: '6',
        max_winding_weight: '500'
    },
    {
        id: 'L1-4',
        category: 'L1',
        flange_diameter: '430',
        barrel_diameter: '200',
        outer_width: '300',
        inner_width: '240',
        shaft_hole: '50',
        weight: '6',
        max_winding_weight: '500'
    },
    {
        id: 'L2-1',
        category: 'L2',
        flange_diameter: '430',
        barrel_diameter: '250',
        outer_width: '300',
        inner_width: '240',
        shaft_hole: '50',
        weight: '7',
        max_winding_weight: '500'
    },
    {
        id: 'L2-2',
        category: 'L2',
        flange_diameter: '460',
        barrel_diameter: '250',
        outer_width: '300',
        inner_width: '240',
        shaft_hole: '50',
        weight: '8',
        max_winding_weight: '500'
    },
    {
        id: 'L2-3',
        category: 'L2',
        flange_diameter: '490',
        barrel_diameter: '250',
        outer_width: '300',
        inner_width: '240',
        shaft_hole: '50',
        weight: '8',
        max_winding_weight: '500'
    },
    {
        id: 'L2-4',
        category: 'L2',
        flange_diameter: '520',
        barrel_diameter: '250',
        outer_width: '300',
        inner_width: '240',
        shaft_hole: '50',
        weight: '9',
        max_winding_weight: '500'
    },
    {
        id: 'L2-5',
        category: 'L2',
        flange_diameter: '550',
        barrel_diameter: '250',
        outer_width: '300',
        inner_width: '240',
        shaft_hole: '50',
        weight: '10',
        max_winding_weight: '500'
    },
    {
        id: 'L3-1',
        category: 'L3',
        flange_diameter: '520',
        barrel_diameter: '300',
        outer_width: '400',
        inner_width: '328',
        shaft_hole: '50',
        weight: '12',
        max_winding_weight: '750'
    },
    {
        id: 'L3-2',
        category: 'L3',
        flange_diameter: '550',
        barrel_diameter: '300',
        outer_width: '400',
        inner_width: '328',
        shaft_hole: '50',
        weight: '13',
        max_winding_weight: '750'
    },
    {
        id: 'L3-3',
        category: 'L3',
        flange_diameter: '580',
        barrel_diameter: '300',
        outer_width: '400',
        inner_width: '328',
        shaft_hole: '50',
        weight: '14',
        max_winding_weight: '750'
    },
    {
        id: 'L3-4',
        category: 'L3',
        flange_diameter: '610',
        barrel_diameter: '300',
        outer_width: '400',
        inner_width: '328',
        shaft_hole: '50',
        weight: '15',
        max_winding_weight: '750'
    },
    {
        id: 'L3-5',
        category: 'L3',
        flange_diameter: '640',
        barrel_diameter: '300',
        outer_width: '400',
        inner_width: '328',
        shaft_hole: '50',
        weight: '16',
        max_winding_weight: '750'
    },
    {
        id: 'L4-1',
        category: 'L4',
        flange_diameter: '610',
        barrel_diameter: '350',
        outer_width: '400',
        inner_width: '328',
        shaft_hole: '50',
        weight: '16',
        max_winding_weight: '750'
    },
    {
        id: 'L4-2',
        category: 'L4',
        flange_diameter: '640',
        barrel_diameter: '350',
        outer_width: '400',
        inner_width: '328',
        shaft_hole: '50',
        weight: '17',
        max_winding_weight: '750'
    },
    {
        id: 'L4-3',
        category: 'L4',
        flange_diameter: '670',
        barrel_diameter: '350',
        outer_width: '400',
        inner_width: '328',
        shaft_hole: '50',
        weight: '18',
        max_winding_weight: '750'
    },
    {
        id: 'L4-4',
        category: 'L4',
        flange_diameter: '700',
        barrel_diameter: '350',
        outer_width: '400',
        inner_width: '328',
        shaft_hole: '50',
        weight: '19',
        max_winding_weight: '750'
    },
    {
        id: 'L4-5',
        category: 'L4',
        flange_diameter: '730',
        barrel_diameter: '350',
        outer_width: '400',
        inner_width: '328',
        shaft_hole: '50',
        weight: '21',
        max_winding_weight: '750'
    },
    {
        id: 'L4-6',
        category: 'L4',
        flange_diameter: '760',
        barrel_diameter: '350',
        outer_width: '400',
        inner_width: '328',
        shaft_hole: '50',
        weight: '22',
        max_winding_weight: '750'
    },
    {
        id: 'L4-7',
        category: 'L4',
        flange_diameter: '790',
        barrel_diameter: '350',
        outer_width: '400',
        inner_width: '328',
        shaft_hole: '50',
        weight: '23',
        max_winding_weight: '750'
    },
    {
        id: 'L5-1',
        category: 'L5',
        flange_diameter: '670',
        barrel_diameter: '400',
        outer_width: '500',
        inner_width: '428',
        shaft_hole: '75',
        weight: '21',
        max_winding_weight: '750'
    },
    {
        id: 'L5-2',
        category: 'L5',
        flange_diameter: '700',
        barrel_diameter: '400',
        outer_width: '500',
        inner_width: '428',
        shaft_hole: '75',
        weight: '22',
        max_winding_weight: '750'
    },
    {
        id: 'L5-3',
        category: 'L5',
        flange_diameter: '730',
        barrel_diameter: '400',
        outer_width: '500',
        inner_width: '428',
        shaft_hole: '75',
        weight: '23',
        max_winding_weight: '750'
    },
    {
        id: 'L5-4',
        category: 'L5',
        flange_diameter: '760',
        barrel_diameter: '400',
        outer_width: '500',
        inner_width: '428',
        shaft_hole: '75',
        weight: '24',
        max_winding_weight: '750'
    },
    {
        id: 'L5-5',
        category: 'L5',
        flange_diameter: '790',
        barrel_diameter: '400',
        outer_width: '500',
        inner_width: '428',
        shaft_hole: '75',
        weight: '25',
        max_winding_weight: '750'
    },
    {
        id: 'L5-6',
        category: 'L5',
        flange_diameter: '820',
        barrel_diameter: '400',
        outer_width: '500',
        inner_width: '428',
        shaft_hole: '75',
        weight: '27',
        max_winding_weight: '750'
    },
    {
        id: 'L6-1',
        category: 'L6',
        flange_diameter: '820',
        barrel_diameter: '450',
        outer_width: '500',
        inner_width: '428',
        shaft_hole: '75',
        weight: '28',
        max_winding_weight: '750'
    },
    {
        id: 'L6-2',
        category: 'L6',
        flange_diameter: '850',
        barrel_diameter: '450',
        outer_width: '500',
        inner_width: '428',
        shaft_hole: '75',
        weight: '30',
        max_winding_weight: '750'
    },
    {
        id: 'L6-3',
        category: 'L6',
        flange_diameter: '880',
        barrel_diameter: '450',
        outer_width: '500',
        inner_width: '428',
        shaft_hole: '75',
        weight: '31',
        max_winding_weight: '750'
    },
    {
        id: 'L6-4',
        category: 'L6',
        flange_diameter: '910',
        barrel_diameter: '450',
        outer_width: '500',
        inner_width: '428',
        shaft_hole: '75',
        weight: '33',
        max_winding_weight: '750'
    },
    {
        id: 'L6-5',
        category: 'L6',
        flange_diameter: '940',
        barrel_diameter: '450',
        outer_width: '500',
        inner_width: '428',
        shaft_hole: '75',
        weight: '34',
        max_winding_weight: '750'
    },
    {
        id: 'L6-6',
        category: 'L6',
        flange_diameter: '970',
        barrel_diameter: '450',
        outer_width: '500',
        inner_width: '428',
        shaft_hole: '75',
        weight: '36',
        max_winding_weight: '750'
    },
    {
        id: 'L7-1',
        category: 'L7',
        flange_diameter: '910',
        barrel_diameter: '500',
        outer_width: '600',
        inner_width: '528',
        shaft_hole: '75',
        weight: '36',
        max_winding_weight: '750'
    },
    {
        id: 'L7-2',
        category: 'L7',
        flange_diameter: '940',
        barrel_diameter: '500',
        outer_width: '600',
        inner_width: '528',
        shaft_hole: '75',
        weight: '38',
        max_winding_weight: '750'
    },
    {
        id: 'L7-3',
        category: 'L7',
        flange_diameter: '970',
        barrel_diameter: '500',
        outer_width: '600',
        inner_width: '528',
        shaft_hole: '75',
        weight: '40',
        max_winding_weight: '750'
    },
    {
        id: 'L7-4',
        category: 'L7',
        flange_diameter: '1000',
        barrel_diameter: '500',
        outer_width: '600',
        inner_width: '528',
        shaft_hole: '75',
        weight: '41',
        max_winding_weight: '750'
    },
    {
        id: 'L7-5',
        category: 'L7',
        flange_diameter: '1050',
        barrel_diameter: '500',
        outer_width: '600',
        inner_width: '528',
        shaft_hole: '75',
        weight: '44',
        max_winding_weight: '750'
    },
    {
        id: 'L8-1',
        category: 'L8',
        flange_diameter: '940',
        barrel_diameter: '600',
        outer_width: '600',
        inner_width: '528',
        shaft_hole: '75',
        weight: '42',
        max_winding_weight: '750'
    },
    {
        id: 'L8-2',
        category: 'L8',
        flange_diameter: '970',
        barrel_diameter: '600',
        outer_width: '600',
        inner_width: '528',
        shaft_hole: '75',
        weight: '43',
        max_winding_weight: '750'
    },
    {
        id: 'L8-3',
        category: 'L8',
        flange_diameter: '1000',
        barrel_diameter: '600',
        outer_width: '600',
        inner_width: '528',
        shaft_hole: '75',
        weight: '45',
        max_winding_weight: '750'
    },
    {
        id: 'L8-4',
        category: 'L8',
        flange_diameter: '1050',
        barrel_diameter: '600',
        outer_width: '600',
        inner_width: '528',
        shaft_hole: '75',
        weight: '48',
        max_winding_weight: '750'
    },
    {
        id: 'L8-5',
        category: 'L8',
        flange_diameter: '1100',
        barrel_diameter: '600',
        outer_width: '600',
        inner_width: '528',
        shaft_hole: '75',
        weight: '51',
        max_winding_weight: '750'
    },
    {
        id: 'L8-6',
        category: 'L8',
        flange_diameter: '1150',
        barrel_diameter: '600',
        outer_width: '600',
        inner_width: '528',
        shaft_hole: '75',
        weight: '54',
        max_winding_weight: '750'
    },
    {
        id: 'L9-1',
        category: 'L9',
        flange_diameter: '1100',
        barrel_diameter: '600',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '72',
        max_winding_weight: '1500'
    },
    {
        id: 'L9-2',
        category: 'L9',
        flange_diameter: '1150',
        barrel_diameter: '600',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '76',
        max_winding_weight: '1500'
    },
    {
        id: 'L9-3',
        category: 'L9',
        flange_diameter: '1200',
        barrel_diameter: '600',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '80',
        max_winding_weight: '1500'
    },
    {
        id: 'L9-4',
        category: 'L9',
        flange_diameter: '1150',
        barrel_diameter: '700',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '82',
        max_winding_weight: '1500'
    },
    {
        id: 'L9-5',
        category: 'L9',
        flange_diameter: '1200',
        barrel_diameter: '700',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '86',
        max_winding_weight: '1500'
    },
    {
        id: 'L9-6',
        category: 'L9',
        flange_diameter: '1250',
        barrel_diameter: '700',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '91',
        max_winding_weight: '1500'
    },
    {
        id: 'L9-7',
        category: 'L9',
        flange_diameter: '1300',
        barrel_diameter: '700',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '96',
        max_winding_weight: '1500'
    },
    {
        id: 'L9-8',
        category: 'L9',
        flange_diameter: '1350',
        barrel_diameter: '700',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '101',
        max_winding_weight: '1500'
    },
    {
        id: 'L10-1',
        category: 'L10',
        flange_diameter: '1250',
        barrel_diameter: '800',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '98',
        max_winding_weight: '1500'
    },
    {
        id: 'L10-2',
        category: 'L10',
        flange_diameter: '1300',
        barrel_diameter: '800',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '103',
        max_winding_weight: '1500'
    },
    {
        id: 'L10-3',
        category: 'L10',
        flange_diameter: '1350',
        barrel_diameter: '800',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '108',
        max_winding_weight: '1500'
    },
    {
        id: 'L10-4',
        category: 'L10',
        flange_diameter: '1400',
        barrel_diameter: '800',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '113',
        max_winding_weight: '1500'
    },
    {
        id: 'L10-5',
        category: 'L10',
        flange_diameter: '1450',
        barrel_diameter: '800',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '119',
        max_winding_weight: '1500'
    },
    {
        id: 'L10-6',
        category: 'L10',
        flange_diameter: '1500',
        barrel_diameter: '800',
        outer_width: '750',
        inner_width: '654',
        shaft_hole: '110',
        weight: '124',
        max_winding_weight: '1500'
    },
    {
        id: 'L11-1',
        category: 'L11',
        flange_diameter: '1400',
        barrel_diameter: '800',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '137',
        max_winding_weight: '2000'
    },
    {
        id: 'L11-2',
        category: 'L11',
        flange_diameter: '1450',
        barrel_diameter: '800',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '143',
        max_winding_weight: '2000'
    },
    {
        id: 'L11-3',
        category: 'L11',
        flange_diameter: '1500',
        barrel_diameter: '800',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '150',
        max_winding_weight: '2000'
    },
    {
        id: 'L11-4',
        category: 'L11',
        flange_diameter: '1550',
        barrel_diameter: '800',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '157',
        max_winding_weight: '2000'
    },
    {
        id: 'L11-5',
        category: 'L11',
        flange_diameter: '1600',
        barrel_diameter: '800',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '165',
        max_winding_weight: '2000'
    },
    {
        id: 'L12-1',
        category: 'L12',
        flange_diameter: '1400',
        barrel_diameter: '900',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '144',
        max_winding_weight: '2000'
    },
    {
        id: 'L12-2',
        category: 'L12',
        flange_diameter: '1450',
        barrel_diameter: '900',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '151',
        max_winding_weight: '2000'
    },
    {
        id: 'L12-3',
        category: 'L12',
        flange_diameter: '1500',
        barrel_diameter: '900',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '158',
        max_winding_weight: '2000'
    },
    {
        id: 'L12-4',
        category: 'L12',
        flange_diameter: '1550',
        barrel_diameter: '900',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '165',
        max_winding_weight: '2000'
    },
    {
        id: 'L12-5',
        category: 'L12',
        flange_diameter: '1600',
        barrel_diameter: '900',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '173',
        max_winding_weight: '2000'
    },
    {
        id: 'L13-1',
        category: 'L13',
        flange_diameter: '1500',
        barrel_diameter: '1000',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '167',
        max_winding_weight: '2000'
    },
    {
        id: 'L13-2',
        category: 'L13',
        flange_diameter: '1550',
        barrel_diameter: '1000',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '174',
        max_winding_weight: '2000'
    },
    {
        id: 'L13-3',
        category: 'L13',
        flange_diameter: '1600',
        barrel_diameter: '1000',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '182',
        max_winding_weight: '2000'
    },
    {
        id: 'L13-4',
        category: 'L13',
        flange_diameter: '1650',
        barrel_diameter: '1000',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '187',
        max_winding_weight: '2000'
    },
    {
        id: 'L13-5',
        category: 'L13',
        flange_diameter: '1700',
        barrel_diameter: '1000',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '197',
        max_winding_weight: '2000'
    },
    {
        id: 'L13-6',
        category: 'L13',
        flange_diameter: '1750',
        barrel_diameter: '1000',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '205',
        max_winding_weight: '2000'
    },
    {
        id: 'L13-7',
        category: 'L13',
        flange_diameter: '1800',
        barrel_diameter: '1000',
        outer_width: '900',
        inner_width: '780',
        shaft_hole: '110',
        weight: '214',
        max_winding_weight: '2000'
    },
    {
        id: 'L14-1',
        category: 'L14',
        flange_diameter: '1700',
        barrel_diameter: '1200',
        outer_width: '1050',
        inner_width: '906',
        shaft_hole: '110',
        weight: '267',
        max_winding_weight: '3000'
    },
    {
        id: 'L14-2',
        category: 'L14',
        flange_diameter: '1750',
        barrel_diameter: '1200',
        outer_width: '1050',
        inner_width: '906',
        shaft_hole: '110',
        weight: '277',
        max_winding_weight: '3000'
    },
    {
        id: 'L14-3',
        category: 'L14',
        flange_diameter: '1800',
        barrel_diameter: '1200',
        outer_width: '1050',
        inner_width: '906',
        shaft_hole: '110',
        weight: '287',
        max_winding_weight: '3000'
    },
    {
        id: 'L14-4',
        category: 'L14',
        flange_diameter: '1850',
        barrel_diameter: '1200',
        outer_width: '1050',
        inner_width: '906',
        shaft_hole: '110',
        weight: '297',
        max_winding_weight: '3000'
    },
    {
        id: 'L14-5',
        category: 'L14',
        flange_diameter: '1900',
        barrel_diameter: '1200',
        outer_width: '1050',
        inner_width: '906',
        shaft_hole: '110',
        weight: '308',
        max_winding_weight: '3000'
    },
    {
        id: 'L14-6',
        category: 'L14',
        flange_diameter: '1950',
        barrel_diameter: '1200',
        outer_width: '1050',
        inner_width: '906',
        shaft_hole: '110',
        weight: '319',
        max_winding_weight: '3000'
    },
    {
        id: 'L14-7',
        category: 'L14',
        flange_diameter: '2000',
        barrel_diameter: '1200',
        outer_width: '1050',
        inner_width: '906',
        shaft_hole: '110',
        weight: '330',
        max_winding_weight: '3000'
    },
    {
        id: 'L15-1',
        category: 'L15',
        flange_diameter: '1900',
        barrel_diameter: '1400',
        outer_width: '1050',
        inner_width: '906',
        shaft_hole: '110',
        weight: '333',
        max_winding_weight: '3000'
    },
    {
        id: 'L15-2',
        category: 'L15',
        flange_diameter: '1950',
        barrel_diameter: '1400',
        outer_width: '1050',
        inner_width: '906',
        shaft_hole: '110',
        weight: '344',
        max_winding_weight: '3000'
    },
    {
        id: 'L15-3',
        category: 'L15',
        flange_diameter: '2000',
        barrel_diameter: '1400',
        outer_width: '1050',
        inner_width: '906',
        shaft_hole: '110',
        weight: '355',
        max_winding_weight: '3000'
    },
    {
        id: 'L15-4',
        category: 'L15',
        flange_diameter: '2100',
        barrel_diameter: '1400',
        outer_width: '1050',
        inner_width: '906',
        shaft_hole: '110',
        weight: '379',
        max_winding_weight: '3000'
    },
    {
        id: 'L16-1',
        category: 'L16',
        flange_diameter: '2000',
        barrel_diameter: '1400',
        outer_width: '1200',
        inner_width: '1056',
        shaft_hole: '110',
        weight: '370',
        max_winding_weight: '3000'
    },
    {
        id: 'L16-2',
        category: 'L16',
        flange_diameter: '2100',
        barrel_diameter: '1400',
        outer_width: '1200',
        inner_width: '1056',
        shaft_hole: '110',
        weight: '393',
        max_winding_weight: '3000'
    },
    {
        id: 'L16-3',
        category: 'L16',
        flange_diameter: '2200',
        barrel_diameter: '1400',
        outer_width: '1200',
        inner_width: '1056',
        shaft_hole: '110',
        weight: '417',
        max_winding_weight: '3000'
    },
    {
        id: 'L16-4',
        category: 'L16',
        flange_diameter: '2300',
        barrel_diameter: '1400',
        outer_width: '1200',
        inner_width: '1056',
        shaft_hole: '110',
        weight: '443',
        max_winding_weight: '3000'
    },
    {
        id: 'L17-1',
        category: 'L17',
        flange_diameter: '2100',
        barrel_diameter: '1600',
        outer_width: '1200',
        inner_width: '1056',
        shaft_hole: '110',
        weight: '422',
        max_winding_weight: '3000'
    },
    {
        id: 'L17-2',
        category: 'L17',
        flange_diameter: '2200',
        barrel_diameter: '1600',
        outer_width: '1200',
        inner_width: '1056',
        shaft_hole: '110',
        weight: '447',
        max_winding_weight: '3000'
    },
    {
        id: 'L17-3',
        category: 'L17',
        flange_diameter: '2300',
        barrel_diameter: '1600',
        outer_width: '1200',
        inner_width: '1056',
        shaft_hole: '110',
        weight: '472',
        max_winding_weight: '3000'
    },
    {
        id: 'L17-4',
        category: 'L17',
        flange_diameter: '2400',
        barrel_diameter: '1600',
        outer_width: '1200',
        inner_width: '1056',
        shaft_hole: '110',
        weight: '499',
        max_winding_weight: '3000'
    },
    {
        id: 'L17-5',
        category: 'L17',
        flange_diameter: '2500',
        barrel_diameter: '1600',
        outer_width: '1200',
        inner_width: '1056',
        shaft_hole: '110',
        weight: '526',
        max_winding_weight: '3000'
    },
    {
        id: 'L17-6',
        category: 'L17',
        flange_diameter: '2600',
        barrel_diameter: '1600',
        outer_width: '1200',
        inner_width: '1056',
        shaft_hole: '110',
        weight: '555',
        max_winding_weight: '3000'
    }
];
