/**
 * プロジェクト内で使用される Lucide アイコンの定義マップ
 * 各アイコンを Vue コンポーネントとして明示的にインポートすることで、
 * Tree-shaking を最大限に活かしつつ、v-html を排除した型安全なアイコン表示を実現します。
 */
import {
  Activity,
  AlignJustify,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Bold,
  Book,
  BookOpen,
  Box,
  Building,
  Calendar,
  Check,
  CheckCheck,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CirclePlus,
  Clipboard,
  Clock,
  CloudUpload,
  Columns,
  Compass,
  Copy,
  Database,
  Delete,
  Disc,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FileSpreadsheet,
  FileText,
  Filter,
  Folder,
  Gauge,
  Hash,
  History,
  Home,
  Inbox,
  Info,
  Key,
  Layout,
  Link,
  List,
  Loader,
  Lock,
  MapPin,
  Menu,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package,
  Plus,
  Power,
  Printer,
  Radio,
  RefreshCw,
  Save,
  Search,
  Settings,
  Slash,
  Sliders,
  Sun,
  Tag,
  Target,
  Terminal,
  Trash2,
  TriangleAlert,
  Type,
  Upload,
  User,
  Users,
  Wifi,
  WifiOff,
  Wrench,
  X,
  Zap,
} from '@lucide/vue'
import type { Component } from 'vue'

export const ICONS: Record<string, Component> = {
  'activity': Activity,
  'align-justify': AlignJustify,
  'archive': Archive,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'bell': Bell,
  'bold': Bold,
  'book': Book,
  'book-open': BookOpen,
  'box': Box,
  'building': Building,
  'calendar': Calendar,
  'check': Check,
  'check-check': CheckCheck,
  'check-square': CheckSquare,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-up-down': ChevronsUpDown,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dot': CircleDot,
  'circle-help': CircleHelp,
  'circle-plus': CirclePlus,
  'clipboard': Clipboard,
  'clock': Clock,
  'cloud-upload': CloudUpload,
  'columns': Columns,
  'compass': Compass,
  'copy': Copy,
  'database': Database,
  'delete': Delete,
  'disc': Disc,
  'download': Download,
  'edit': Edit,
  'external-link': ExternalLink,
  'eye': Eye,
  'eye-off': EyeOff,
  'file': File,
  'file-check': FileCheck,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  'filter': Filter,
  'folder': Folder,
  'gauge': Gauge,
  'hash': Hash,
  'history': History,
  'home': Home,
  'inbox': Inbox,
  'info': Info,
  'key': Key,
  'layout': Layout,
  'link': Link,
  'list': List,
  'loader': Loader,
  'lock': Lock,
  'map-pin': MapPin,
  'menu': Menu,
  'minus': Minus,
  'moon': Moon,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'package': Package,
  'plus': Plus,
  'power': Power,
  'printer': Printer,
  'radio': Radio,
  'refresh-cw': RefreshCw,
  'save': Save,
  'search': Search,
  'settings': Settings,
  'slash': Slash,
  'sliders': Sliders,
  'sun': Sun,
  'tag': Tag,
  'target': Target,
  'terminal': Terminal,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  'type': Type,
  'upload': Upload,
  'user': User,
  'users': Users,
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'wrench': Wrench,
  'x': X,
  'zap': Zap,
}

export type IconName = keyof typeof ICONS
