/**
 * プロジェクト内で使用される Lucide アイコンの定義マップ
 * 各アイコンを Vue コンポーネントとして明示的にインポートすることで、
 * Tree-shaking を最大限に活かしつつ、v-html を排除した型安全なアイコン表示を実現します。
 */
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  AlignJustify,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Bold,
  Book,
  BookOpen,
  Box,
  Calendar,
  Check,
  CheckCheck,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clipboard,
  Clock,
  Columns,
  Copy,
  Database,
  Delete,
  Disc,
  Download,
  Edit,
  ExternalLink,
  File,
  FileCheck,
  FileSpreadsheet,
  Filter,
  Folder,
  Hash,
  HelpCircle,
  History,
  Home,
  Inbox,
  Info,
  Link,
  List,
  Loader,
  MapPin,
  Menu,
  Minus,
  Moon,
  Package,
  Plus,
  Power,
  Radio,
  RefreshCw,
  Save,
  Search,
  Settings,
  Sliders,
  Sun,
  Tag,
  Target,
  Terminal,
  Trash2,
  Type,
  Upload,
  UploadCloud,
  User,
  Users,
  Wifi,
  WifiOff,
  Wrench,
  X,
  Zap,
} from '@lucide/vue'
import type { Component } from 'vue'

export const ICONS: Record<string, Component> = {
  'activity': Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'align-justify': AlignJustify,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'bell': Bell,
  'bold': Bold,
  'book': Book,
  'book-open': BookOpen,
  'box': Box,
  'calendar': Calendar,
  'check': Check,
  'check-check': CheckCheck,
  'check-circle': CheckCircle,
  'check-square': CheckSquare,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'clipboard': Clipboard,
  'clock': Clock,
  'columns': Columns,
  'copy': Copy,
  'database': Database,
  'delete': Delete,
  'disc': Disc,
  'download': Download,
  'edit': Edit,
  'external-link': ExternalLink,
  'file': File,
  'file-check': FileCheck,
  'file-spreadsheet': FileSpreadsheet,
  'filter': Filter,
  'folder': Folder,
  'hash': Hash,
  'help-circle': HelpCircle,
  'history': History,
  'home': Home,
  'inbox': Inbox,
  'info': Info,
  'link': Link,
  'list': List,
  'loader': Loader,
  'map-pin': MapPin,
  'menu': Menu,
  'minus': Minus,
  'moon': Moon,
  'package': Package,
  'plus': Plus,
  'power': Power,
  'radio': Radio,
  'refresh-cw': RefreshCw,
  'save': Save,
  'search': Search,
  'settings': Settings,
  'sliders': Sliders,
  'sun': Sun,
  'tag': Tag,
  'target': Target,
  'terminal': Terminal,
  'tool': Wrench,
  'trash-2': Trash2,
  'type': Type,
  'upload': Upload,
  'upload-cloud': UploadCloud,
  'user': User,
  'users': Users,
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'wrench': Wrench,
  'x': X,
  'zap': Zap,
}

export type IconName = keyof typeof ICONS
